package life.majiang.community.model;

import java.util.Date;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.ID
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.USER_NAME
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.HEAD_URL
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    private String headUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.IS_FOCUS
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    private Boolean isFocus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.NEWS_TITLE
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    private String newsTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.IS_VIDEO
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    private Boolean isVideo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.VIDEO_URL
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.NEWS_ABSTRACK
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    private String newsAbstrack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.IS_ORIGINAL
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    private Boolean isOriginal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.CREATE_TIME
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.NEWS_TEXT
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    private String newsText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.ID
     *
     * @return the value of NEWS.ID
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.ID
     *
     * @param id the value for NEWS.ID
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.USER_NAME
     *
     * @return the value of NEWS.USER_NAME
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.USER_NAME
     *
     * @param userName the value for NEWS.USER_NAME
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.HEAD_URL
     *
     * @return the value of NEWS.HEAD_URL
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.HEAD_URL
     *
     * @param headUrl the value for NEWS.HEAD_URL
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.IS_FOCUS
     *
     * @return the value of NEWS.IS_FOCUS
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public Boolean getIsFocus() {
        return isFocus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.IS_FOCUS
     *
     * @param isFocus the value for NEWS.IS_FOCUS
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public void setIsFocus(Boolean isFocus) {
        this.isFocus = isFocus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.NEWS_TITLE
     *
     * @return the value of NEWS.NEWS_TITLE
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.NEWS_TITLE
     *
     * @param newsTitle the value for NEWS.NEWS_TITLE
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle == null ? null : newsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.IS_VIDEO
     *
     * @return the value of NEWS.IS_VIDEO
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public Boolean getIsVideo() {
        return isVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.IS_VIDEO
     *
     * @param isVideo the value for NEWS.IS_VIDEO
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public void setIsVideo(Boolean isVideo) {
        this.isVideo = isVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.VIDEO_URL
     *
     * @return the value of NEWS.VIDEO_URL
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.VIDEO_URL
     *
     * @param videoUrl the value for NEWS.VIDEO_URL
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.NEWS_ABSTRACK
     *
     * @return the value of NEWS.NEWS_ABSTRACK
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public String getNewsAbstrack() {
        return newsAbstrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.NEWS_ABSTRACK
     *
     * @param newsAbstrack the value for NEWS.NEWS_ABSTRACK
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public void setNewsAbstrack(String newsAbstrack) {
        this.newsAbstrack = newsAbstrack == null ? null : newsAbstrack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.IS_ORIGINAL
     *
     * @return the value of NEWS.IS_ORIGINAL
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public Boolean getIsOriginal() {
        return isOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.IS_ORIGINAL
     *
     * @param isOriginal the value for NEWS.IS_ORIGINAL
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public void setIsOriginal(Boolean isOriginal) {
        this.isOriginal = isOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.CREATE_TIME
     *
     * @return the value of NEWS.CREATE_TIME
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.CREATE_TIME
     *
     * @param createTime the value for NEWS.CREATE_TIME
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.NEWS_TEXT
     *
     * @return the value of NEWS.NEWS_TEXT
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public String getNewsText() {
        return newsText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.NEWS_TEXT
     *
     * @param newsText the value for NEWS.NEWS_TEXT
     *
     * @mbg.generated Mon Mar 30 20:48:12 CST 2020
     */
    public void setNewsText(String newsText) {
        this.newsText = newsText == null ? null : newsText.trim();
    }
}